In [8]:
import pandas as pd
import numpy as np

url = "C:/Users/Gumede/Downloads/bky6-3za5.csv"
df = pd.read_csv(url)

print(df.head())

    is_cluster  pocket_name                pocket_alias   ward_id  \
0       4 in 1       4 in 1  Wallacedene 14 / J Section  19100006
1  Acacia Road  Acacia Road      Acacia Park - Parktown  19100066
2    Amy Biehl    Amy Biehl                 School Site  19100034
3  Appel Boord  Appel Boord                         NaN  19100022
4       Area K       Area K                 Never Never  19100088

           ward_councillor  avg_hhsize  area_ha  density_dwellings  \
0      Simpiwe Nonkeyizana        3.72    2.952          50.813008
1          Melanie Arendse        4.51    0.070         114.285714
2         Fikiswa Nkunzana        2.89    1.711         301.578025
3          Johanna Martlow        4.14    0.088         159.090909
4  Patrick (Pat) Pietersen        4.17    2.661         249.154453

   structure_count      age_of_is  ... toilets_full_flush  toilets_chemical  \
0              150  15 - 20 years  ...               32.0               0.0
1                8  10 - 15 years  ...                3.0               2.0
2              516  15 - 20 years  ...               93.0               0.0
3               14   5 - 10 years  ...               10.0               0.0
4              663  10 - 15 years  ...              121.0               0.0

   toilets_portable  toilets_container  toilets_other  toilets_total  \
0               0.0                0.0            0.0           32.0
1               0.0                0.0            0.0            5.0
2               0.0                0.0            0.0           93.0
3               0.0                0.0            0.0           10.0
4               0.0                0.0            0.0          121.0

   ratio_toilets_dwellings  pocket_code  centroidx  centroidy
0                      1:5    NORFOU001  18.732603 -33.863384
1                      1:2    HILACA001  18.501024 -34.032822
2                      1:6    MITAMY001  18.587852 -34.002772
3                      1:1    TYGAPP001  18.609142 -33.926268
4                      1:5    MITARE001  18.598543 -34.008208

[5 rows x 22 columns]

In [2]:
print("Shape of the dataset:", df.shape)
print("\nData types of each column:\n", df.dtypes)
print("\nColumns in the dataset:\n", df.columns)

# Summary statistics
print("\nSummary statistics:\n", df.describe(include='all'))

# Specific column
print("\nUnique values in 'Ward Councillor' column:\n", df['ward_councillor'].unique())

Shape of the dataset: (434, 22)

Data types of each column:
 is_cluster                  object
pocket_name                 object
pocket_alias                object
ward_id                      int64
ward_councillor             object
avg_hhsize                 float64
area_ha                    float64
density_dwellings          float64
structure_count              int64
age_of_is                   object
upgrade_category            object
temp_sanitation            float64
toilets_full_flush         float64
toilets_chemical           float64
toilets_portable           float64
toilets_container          float64
toilets_other              float64
toilets_total              float64
ratio_toilets_dwellings     object
pocket_code                 object
centroidx                  float64
centroidy                  float64
dtype: object

Columns in the dataset:
 Index(['is_cluster', 'pocket_name', 'pocket_alias', 'ward_id',
       'ward_councillor', 'avg_hhsize', 'area_ha', 'density_dwellings',
       'structure_count', 'age_of_is', 'upgrade_category', 'temp_sanitation',
       'toilets_full_flush', 'toilets_chemical', 'toilets_portable',
       'toilets_container', 'toilets_other', 'toilets_total',
       'ratio_toilets_dwellings', 'pocket_code', 'centroidx', 'centroidy'],
      dtype='object')

Summary statistics:
                 is_cluster pocket_name         pocket_alias       ward_id  \
count                  434         434                  192  4.340000e+02
unique                 202         434                  186           NaN
top     Crossroads Infills      4 in 1  Crossroads 13/14/16           NaN
freq                    22           1                    3           NaN
mean                   NaN         NaN                  NaN  1.910006e+07
std                    NaN         NaN                  NaN  3.102414e+01
min                    NaN         NaN                  NaN  1.910000e+07
25%                    NaN         NaN                  NaN  1.910004e+07
50%                    NaN         NaN                  NaN  1.910007e+07
75%                    NaN         NaN                  NaN  1.910009e+07
max                    NaN         NaN                  NaN  1.910011e+07

         ward_councillor  avg_hhsize     area_ha  density_dwellings  \
count                434  434.000000  434.000000         434.000000
unique                74         NaN         NaN                NaN
top     Thembinkosi Pupa         NaN         NaN                NaN
freq                  27         NaN         NaN                NaN
mean                 NaN    3.337143    4.462938         183.057795
std                  NaN    0.535691   32.968974         182.105873
min                  NaN    2.190000    0.010000           0.000000
25%                  NaN    2.892500    0.140000          90.022903
50%                  NaN    3.230000    0.389000         174.685262
75%                  NaN    3.710000    1.904000         254.274750
max                  NaN    5.110000  669.406000        3007.299270

        structure_count      age_of_is  ... toilets_full_flush  \
count        434.000000            434  ...         434.000000
unique              NaN              5  ...                NaN
top                 NaN  15 - 20 years  ...                NaN
freq                NaN            183  ...                NaN
mean         337.744240            NaN  ...          31.283410
std          859.580015            NaN  ...          87.902084
min            0.000000            NaN  ...           0.000000
25%           21.000000            NaN  ...           0.000000
50%           53.000000            NaN  ...           4.000000
75%          289.500000            NaN  ...          16.000000
max         7963.000000            NaN  ...        1095.000000

        toilets_chemical  toilets_portable  toilets_container  toilets_other  \
count         434.000000        434.000000         434.000000     434.000000
unique               NaN               NaN                NaN            NaN
top                  NaN               NaN                NaN            NaN
freq                 NaN               NaN                NaN            NaN
mean           11.582949         36.700461          11.698157       2.836406
std            48.968423        205.429506          73.071471      28.036655
min             0.000000          0.000000           0.000000       0.000000
25%             0.000000          0.000000           0.000000       0.000000
50%             0.000000          0.000000           0.000000       0.000000
75%             0.000000          0.000000           0.000000       0.000000
max           578.000000       3109.000000         883.000000     525.000000

        toilets_total  ratio_toilets_dwellings  pocket_code   centroidx  \
count      434.000000                      343          434  434.000000
unique            NaN                       31          434         NaN
top               NaN                      1:1    NORFOU001         NaN
freq              NaN                       53            1         NaN
mean        94.101382                      NaN          NaN   18.603335
std        314.532145                      NaN          NaN    0.106208
min          0.000000                      NaN          NaN   18.341108
25%          3.000000                      NaN          NaN   18.544694
50%         10.000000                      NaN          NaN   18.590699
75%         57.500000                      NaN          NaN   18.662143
max       4807.000000                      NaN          NaN   18.910236

         centroidy
count   434.000000
unique         NaN
top            NaN
freq           NaN
mean    -33.987186
std       0.099290
min     -34.202636
25%     -34.025843
50%     -34.005508
75%     -33.985590
max     -33.538179

[11 rows x 22 columns]

Unique values in 'Ward Councillor' column:
 ['Simpiwe Nonkeyizana' 'Melanie Arendse' 'Fikiswa Nkunzana'
 'Johanna Martlow' 'Patrick (Pat) Pietersen' 'Barbara Rass'
 'Cynthia Clayton' 'Khaya Yozi' 'Shaun August' 'Jongidumo Maxheke'
 'Thembinkosi Pupa' 'Monde Nqulwana' 'Dave Bryant' 'Ntomboxolo Kopman'
 'Mlulami Velem' 'Monty Oliver' 'Gordon Thomas' 'Depoutch Elese'
 'Nico Mzalisi' 'Themba Honono' 'Eddie Andrews' 'Amos Komeni'
 'Johannes (Johan) Middleton' 'Jan Burger' 'Khayalethu Makeleni'
 'Lubabalo Makeleni' 'John Heuvel' '(Botsotso) Danile Khatshwa'
 'Brian Watkyns' 'Justin Basson' 'Anthea Green' 'Marita Petersen'
 'Asa Abrahams' 'Richard O Connell' 'Gerhard Fourie' 'Cynthia Claasen'
 'Siyabulela Mamkeli' 'Anthony Moses' 'Marian Nieuwoudt' 'Magedien Davids'
 'Marga Haywood' 'Bert Van Dalen' 'Anele Gabuza' 'Neliswa Ngqose'
 'Luvuyo Hebe' 'Mayenzeke Sopaqa' 'Jacob Jacobs' 'Mzwakhe Nqavashe'
 'Nora Grose' 'Mzuzile Mpondwana' 'Lisa McBride' 'Siseko Mbandezi'
 'Theophilus Mangali' 'Leslie Isaacs' 'Monde Mabandla'
 'Coetzee Ntotoviyane' 'Felicity Purchase' 'Joy McCarthy' 'Mpucuko Nguzo'
 'Mbuyiselo Matha' "David D'Alton" 'Luvuyo Zondani' 'Brett Herron'
 'Simon Liell-Cock' 'Shanen Rossouw' 'Natalie Bent' 'Benedicta van Minnen'
 'Elton-Enrique Jansen' 'Beverley van Reenen' 'Maneli Msindwana'
 'Nomvuyo Mofoko' 'Nas Abrahams' 'Brenda Hansen' 'Mthwalo Mkutswana']

In [3]:
# Checking for missing data
missing_data = df.isnull().sum()
print("\nMissing data in each column:\n", missing_data)

missing_percentage = (df.isnull().sum() / df.shape[0]) * 100
print("\nPercentage of missing data in each column:\n", missing_percentage)

Missing data in each column:
 is_cluster                   0
pocket_name                  0
pocket_alias               242
ward_id                      0
ward_councillor              0
avg_hhsize                   0
area_ha                      0
density_dwellings            0
structure_count              0
age_of_is                    0
upgrade_category             0
temp_sanitation              0
toilets_full_flush           0
toilets_chemical             0
toilets_portable             0
toilets_container            0
toilets_other                0
toilets_total                0
ratio_toilets_dwellings     91
pocket_code                  0
centroidx                    0
centroidy                    0
dtype: int64

Percentage of missing data in each column:
 is_cluster                  0.000000
pocket_name                 0.000000
pocket_alias               55.760369
ward_id                     0.000000
ward_councillor             0.000000
avg_hhsize                  0.000000
area_ha                     0.000000
density_dwellings           0.000000
structure_count             0.000000
age_of_is                   0.000000
upgrade_category            0.000000
temp_sanitation             0.000000
toilets_full_flush          0.000000
toilets_chemical            0.000000
toilets_portable            0.000000
toilets_container           0.000000
toilets_other               0.000000
toilets_total               0.000000
ratio_toilets_dwellings    20.967742
pocket_code                 0.000000
centroidx                   0.000000
centroidy                   0.000000
dtype: float64

In [9]:
from sklearn.preprocessing import StandardScaler

#Converting ratio strings to numeric values
def convert_ratio_to_numeric(ratio_value):
    if pd.isna(ratio_value):
        return None
    if isinstance(ratio_value, str):
        try:
            numerator, denominator = map(int, ratio_value.split(':'))
            if denominator == 0:
                return None
            return numerator / denominator
        except (ValueError, TypeError):
            return None
    elif isinstance(ratio_value, float):
        return ratio_value
    else:
        return None

# Converting the 'ratio_toilets_dwellings' column to numeric
df['ratio_toilets_dwellings'] = df['ratio_toilets_dwellings'].apply(convert_ratio_to_numeric)

# Filling missing data with median for numerical columns
df['ratio_toilets_dwellings'] = df['ratio_toilets_dwellings'].fillna(df['ratio_toilets_dwellings'].median())

# Droping rows with missing values in critical columns
df = df.dropna(subset=['pocket_name'])

# Checking if 'pocket_alias' exists before attempting to drop it
if 'pocket_alias' in df.columns:
    df = df.drop(columns=['pocket_alias'])

# Standardize the 'ratio_toilets_dwellings' column
scaler = StandardScaler()
df['ratio_toilets_dwellings'] = scaler.fit_transform(df[['ratio_toilets_dwellings']])

# Cleaned dataset
print("\nCleaned dataset:\n", df.head())

# Missing data information after cleaning
missing_data = df.isnull().sum()
print("\nMissing data in each column after cleaning:\n", missing_data)
missing_data_percentage = (missing_data / df.shape[0]) * 100
print("\nPercentage of missing data in each column after cleaning:\n", missing_data_percentage)

Cleaned dataset:
     is_cluster  pocket_name   ward_id          ward_councillor  avg_hhsize  \
0       4 in 1       4 in 1  19100006      Simpiwe Nonkeyizana        3.72
1  Acacia Road  Acacia Road  19100066          Melanie Arendse        4.51
2    Amy Biehl    Amy Biehl  19100034         Fikiswa Nkunzana        2.89
3  Appel Boord  Appel Boord  19100022          Johanna Martlow        4.14
4       Area K       Area K  19100088  Patrick (Pat) Pietersen        4.17

   area_ha  density_dwellings  structure_count      age_of_is  \
0    2.952          50.813008              150  15 - 20 years
1    0.070         114.285714                8  10 - 15 years
2    1.711         301.578025              516  15 - 20 years
3    0.088         159.090909               14   5 - 10 years
4    2.661         249.154453              663  10 - 15 years

                                    upgrade_category  ...  toilets_full_flush  \
0                         City land. Can be upgraded  ...                32.0
1        Many constraints.  May need to be relocated  ...                 3.0
2  Provincial or National government land.  Some ...  ...                93.0
3                         City land. Can be upgraded  ...                10.0
4  Provincial or National government land.  Some ...  ...               121.0

   toilets_chemical  toilets_portable  toilets_container  toilets_other  \
0               0.0               0.0                0.0            0.0
1               2.0               0.0                0.0            0.0
2               0.0               0.0                0.0            0.0
3               0.0               0.0                0.0            0.0
4               0.0               0.0                0.0            0.0

   toilets_total  ratio_toilets_dwellings  pocket_code  centroidx  centroidy
0           32.0                -0.471630    NORFOU001  18.732603 -33.863384
1            5.0                 0.616613    HILACA001  18.501024 -34.032822
2           93.0                -0.592546    MITAMY001  18.587852 -34.002772
3           10.0                 2.430351    TYGAPP001  18.609142 -33.926268
4          121.0                -0.471630    MITARE001  18.598543 -34.008208

[5 rows x 21 columns]

Missing data in each column after cleaning:
 is_cluster                 0
pocket_name                0
ward_id                    0
ward_councillor            0
avg_hhsize                 0
area_ha                    0
density_dwellings          0
structure_count            0
age_of_is                  0
upgrade_category           0
temp_sanitation            0
toilets_full_flush         0
toilets_chemical           0
toilets_portable           0
toilets_container          0
toilets_other              0
toilets_total              0
ratio_toilets_dwellings    0
pocket_code                0
centroidx                  0
centroidy                  0
dtype: int64

Percentage of missing data in each column after cleaning:
 is_cluster                 0.0
pocket_name                0.0
ward_id                    0.0
ward_councillor            0.0
avg_hhsize                 0.0
area_ha                    0.0
density_dwellings          0.0
structure_count            0.0
age_of_is                  0.0
upgrade_category           0.0
temp_sanitation            0.0
toilets_full_flush         0.0
toilets_chemical           0.0
toilets_portable           0.0
toilets_container          0.0
toilets_other              0.0
toilets_total              0.0
ratio_toilets_dwellings    0.0
pocket_code                0.0
centroidx                  0.0
centroidy                  0.0
dtype: float64